// Notifications inbox
// color: signal-amber for parking/general, alert-red for theft/emergency, verified-green for resolved
export const notifications = [
  {
    id: 'n1',
    type: 'Wrong Parking',
    vehicleId: 'v1',
    vehicle: 'Honda Activa',
    plate: 'MH 14 AB 1234',
    time: '10 min ago',
    timestamp: '2026-07-03T10:47:00',
    colorClass: 'signal-amber',
    color: '#F5A623',
    isAlert: false,
    read: false,
    resolved: false,
    notes: 'Blocking the main gate entrance, please move immediately.',
    location: 'Kalyani Nagar, Pune',
    lat: 18.5452,
    lng: 73.9022,
    locationShared: true,
    photoAttached: false,
    reporter: 'Anonymous',
    emoji: '🅿️',
  },
  {
    id: 'n2',
    type: 'Vehicle Theft',
    vehicleId: 'v1',
    vehicle: 'Honda Activa',
    plate: 'MH 14 AB 1234',
    time: '1 hr ago',
    timestamp: '2026-07-03T09:57:00',
    colorClass: 'alert-red',
    color: '#D93025',
    isAlert: true,
    read: false,
    resolved: false,
    notes: 'Someone is trying to tow the vehicle near the parking lot.',
    location: 'Viman Nagar, Pune',
    lat: 18.5679,
    lng: 73.9143,
    locationShared: true,
    photoAttached: false,
    reporter: 'Anonymous',
    emoji: '🚨',
  },
  {
    id: 'n3',
    type: 'Headlights On',
    vehicleId: 'v1',
    vehicle: 'Honda Activa',
    plate: 'MH 14 AB 1234',
    time: 'Yesterday',
    timestamp: '2026-07-02T18:30:00',
    colorClass: 'signal-amber',
    color: '#F5A623',
    isAlert: false,
    read: true,
    resolved: true,
    notes: 'Your headlights have been left on in the office parking.',
    location: null,
    locationShared: false,
    photoAttached: false,
    reporter: 'Anonymous',
    emoji: '💡',
  },
  {
    id: 'n4',
    type: 'Document Expiring',
    vehicleId: 'v1',
    vehicle: 'Insurance',
    plate: 'MH 14 AB 1234',
    time: '2 days ago',
    timestamp: '2026-07-01T09:00:00',
    colorClass: 'alert-red',
    color: '#D93025',
    isAlert: false,
    read: true,
    resolved: false,
    notes: 'Your vehicle insurance expires in 12 days. Renew now to stay covered.',
    location: null,
    locationShared: false,
    photoAttached: false,
    reporter: 'System',
    emoji: '📄',
  },
  {
    id: 'n5',
    type: 'Vehicle Verified',
    vehicleId: 'v2',
    vehicle: 'Royal Enfield Classic 350',
    plate: 'MH 12 XY 5678',
    time: '3 days ago',
    timestamp: '2026-06-30T14:00:00',
    colorClass: 'verified-green',
    color: '#1E8E5A',
    isAlert: false,
    read: true,
    resolved: true,
    notes: 'Your vehicle identity has been verified and is now active on RoadLink.',
    location: null,
    locationShared: false,
    photoAttached: false,
    reporter: 'RoadLink',
    emoji: '✅',
  },
];
